ASP.NET Core Empty Project/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using ASP.NET_Core_Empty_Project.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP.NET_Core_Empty_Project.Models;
using Microsoft.AspNetCore.Authorization;

namespace ASP.NET_Core_Empty_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CountryController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var data = _context.Countries.ToList();
            return View(data);
        }
        public IActionResult CreateCountry()
        {
            return View();
        }
        public IActionResult EditCountry()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCountry(CountryDb country)
        {
            if (ModelState.IsValid)
            {
                _context.Countries.Add(country);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpPost]
        public IActionResult DeleteCountry(int id)
        {
            var country = _context.Countries.Find(id);
            _context.Remove(country);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult EditCountry(EditCountryVM vm)
        {
            if (ModelState.IsValid)
            {
                var country = _context.Countries.Find(vm.Id);
                if (country != null)
                {
                    country.Name = vm.Name;
                }
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ASP.NET Core Empty Project/Views/Country/CreateCountry.cshtml
@model CountryDb
@{
    ViewData["Title"] = "CreateCountry";
}

<div class="container">
    <h2>Create country</h2>

    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="CreateCountry">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back country List</a>
    </div>


</div>
    </div>

ASP.NET Core Empty Project/Views/Country/EditCountry.cshtml
@model EditCountryVM
@{
    ViewData["Title"] = "EditCountry";
}

<h2>EditCountry</h2>


<div class="container">
    <h2>Edit country</h2>

    <hr /><form asp-controller="Country" asp-action="EditCountry" method="post" class="form p-5 border border-secondary">
    <h4 class="form-text">Edit Country</h4>
    <div class="form-group">
        <label asp-for="Id" class="control-label"></label>
        <input asp-for="Id" class="form-control" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input class="form-control" asp-for="Name" />
                <span class="alert-danger" asp-validation-for="Name"></span>
            </div>
            <button class="form-control btn btn-primary" type="submit"> Update Country </button>
</form>
    

    <div>
        <a asp-action="Index">Back country List</a>
    </div>


</div>

ASP.NET Core Empty Project/Views/Country/Index.cshtml
@model IEnumerable<CountryDb>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <h1>Countries</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                </tr>
            }
        </tbody>
    </table>
    <a class="btn btn-primary" asp-area="" asp-controller="Country" asp-action="CreateCountry">Create a country</a>
    <a class="btn btn-primary" asp-area="" asp-controller="Country" asp-action="EditCountry">Edit a country</a>

    <form asp-controller="Country" asp-action="DeleteCountry" method="post" role="form">
        <br />
        <label for="ssn">Enter country Id for deletion:</label>
        <input type="text" name="id" />
        <input type="submit" class="btn btn-primary" name="btnFilter" value="delete" />
    </form>
</div>