ASP.NET Core Empty Project/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using ASP.NET_Core_Empty_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Empty_Project.Controllers
{
    public class DoctorController : Controller
    {
        public IActionResult FeverCheck() //get 
        {
             ViewBag.Message = FeverModel.WriteMessage();
            return View();
        }

        [HttpPost]
        public IActionResult FeverCheck(int temp) //get 
        {
            FeverModel fm = new FeverModel();
            fm.Temp = temp;

            ViewBag.Message = fm.CheckTemp(temp);
            return View();

        }
    }
}

ASP.NET Core Empty Project/Views/Doctor/FeverCheck.cshtml
@{
    ViewData["Title"] = "FeverCheck";
}
<div class="container">

    @if (ViewBag.Message != null)
    {
        <p>@ViewBag.Message </p>
    }
    <form asp-controller="Doctor" , asp-action="FeverCheck" method="post">

        <label>Temprature:</label>
        <input type="number" name="temp" />
        <input type="submit" value="Create" />
    </form>
</div>

ASP.NET Core Empty Project/Views/Doctor/TempCheck.cshtml
@{
    ViewData["Title"] = "TempCheck";
}

<h2>TempCheck</h2>

@if (ViewBag.Message != null)
{
    <p>@ViewBag.Message </p>
}
<form asp-controller="Doctor" , asp-action="FeverModel" method="post">

    <label>Temprature:</label>
    <input type="number" name="temp" />
    <input type="submit" value="Create" />

</form>