ASP.NET Core Empty Project/Controllers/CityController.cs
using ASP.NET_Core_Empty_Project.Data;
using ASP.NET_Core_Empty_Project.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Empty_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CityController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CityController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var listOfCitys = _context.Cities.ToList();
            return View(listOfCitys);
        }
        public IActionResult CreateCity()
        {
            return View();
        }
        public IActionResult EditCity()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCity(CityDb city)
        {
            if (ModelState.IsValid)
            {
                _context.Cities.Add(city);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpPost]
        public IActionResult DeleteCity(int id)
        {
            var city = _context.Cities.Find(id);
            _context.Remove(city);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult EditCity(EditCityVm vm)
        {
            if (ModelState.IsValid)
            {
                var city = _context.Cities.Find(vm.Id);
                if (city != null)
                {
                    city.Name = vm.Name;
                    city.CountryId = vm.CountryId;
                }
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ASP.NET Core Empty Project/Views/City/CreateCity.cshtml
@model CityDb
@{
    ViewData["Title"] = "CreateCity";
}

<div class="container">
    <h2>Create a city</h2>

    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="CreateCity">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CountryId" class="control-label"></label>
                    <input asp-for="CountryId" class="form-control" />
                    <span asp-validation-for="CountryId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back country List</a>
    </div>


</div>
    </div>

ASP.NET Core Empty Project/Views/City/EditCity.cshtml
@model EditCityVm
@{
    ViewData["Title"] = "EditCity";
}

<h2>Edit City</h2>


<div class="container">
    <h2>Edit city</h2>

    <hr /><form asp-controller="city" asp-action="EditCity" method="post" class="form p-5 border border-secondary">
    <h4 class="form-text">Edit City</h4>
    <div class="form-group">
        <label asp-for="Id" class="control-label"></label>
        <input asp-for="Id" class="form-control" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="alert-danger" asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="CountryId"></label>
        <input class="form-control" asp-for="CountryId" />
        <span class="alert-danger" asp-validation-for="CountryId"></span>
    </div>
    <button class="form-control btn btn-primary" type="submit"> Update City </button>
    
</form>


    <div>
        <a asp-action="Index">Back city List</a>
    </div>


</div>

ASP.NET Core Empty Project/Views/City/Index.cshtml
@model IEnumerable<CityDb>
@{
    ViewData["Title"] = "Index";
}


<div class="container">
    <h1>Cities</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Country Code</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.CountryId</td>
                </tr>
            }
        </tbody>
    </table>
    <a class="btn btn-primary" asp-area="" asp-controller="city" asp-action="CreateCity">Create a City</a>
    <a class="btn btn-primary" asp-area="" asp-controller="City" asp-action="EditCity">Edit a city</a>
    <form asp-controller="City" asp-action="DeleteCity" method="post" role="form">
        <br />
        <label for="ssn">Enter cityId for deletion:</label>
        <input type="text" name="id" />
        <input type="submit" class="btn btn-primary" name="btnFilter" value="delete" />
    </form>
</div>