ASP.NET Core Empty Project/Models/CreatePersonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace ASP.NET_Core_Empty_Project.Models
{
    public class CreatePersonViewModel
    {
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter a name"),  MinLength(3)]
        [Display(Name =" Name")]
        public string Name { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter a phone number"),  MinLength(3)]
        [Display(Name = "Phone Number")]
        public string PhoneNr { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter a a city name"),  MinLength(3)]
        [Display(Name = "City Id")]
        public int CityId { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter a social security number"), MinLength(13)]
        [Display(Name = "SSN")]
        public string SSN { get; set; }
    }
}

ASP.NET Core Empty Project/Controllers/PeopleDbController.cs
using ASP.NET_Core_Empty_Project.Data;
using ASP.NET_Core_Empty_Project.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Core_Empty_Project.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class PeopleDbController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PeopleDbController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            PeopleViewModelDb vm = new PeopleViewModelDb() { PeopleListView = _context.People.ToList() };
            return View(vm);
        }
        public IActionResult CreatePerson()
        {
            return View();
        }
        public IActionResult EditPerson()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreatePerson(PersonDb person)
        {
            if (ModelState.IsValid)
            {
                _context.People.Add(person);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpPost]
        public IActionResult EditPerson(EditPersonVM vm)
        {
            
                var person = _context.People.Find(vm.SSN);
                if (person != null)
                {
                    person.Name = vm.Name;
                    person.CityId = vm.CityId;
                    person.PhoneNr = vm.PhoneNumber;
                }
                _context.SaveChanges();
            

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult DeletePerson(string ssn)
        {
            var person = _context.People.Find(ssn);
            _context.Remove(person);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

ASP.NET Core Empty Project/Views/PeopleDb/CreatePerson.cshtml
@model PeopleViewModelDb
@{
    ViewData["Title"] = "CreatePerson";
}
<div class="container">

    <h2>CreatePerson</h2>

    <hr />
    <form asp-controller="PeopleDb" asp-action="CreatePerson" method="post">
        <label asp-for="Name"></label>
        <br />
        <input asp-for="Name" />
        <br />
        <label asp-for="PhoneNr"></label>
        <br />
        <input asp-for="PhoneNr" />
        <br />
        <label asp-for="SSN"></label>
        <br />
        <input asp-for="SSN" />
        <br />
        <label asp-for="CityId"></label>
        <br />
        <input asp-for="CityId" />
        <br />
        <input type="submit" value="Create person" />
        <br />
    </form>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

ASP.NET Core Empty Project/Views/PeopleDb/EditPerson.cshtml
@model EditPersonVM
@{
    ViewData["Title"] = "EditPerson";
}

<h2>Edit Person</h2>


<div class="container">

    <hr /><form asp-controller="PeopleDb" asp-action="EditPerson" method="post" class="form p-5 border border-secondary">
    <h4 class="form-text">Edit Person</h4>
    <div class="form-group">
        <label asp-for="SSN" class="control-label"></label>
        <input asp-for="SSN" class="form-control" />
        <span asp-validation-for="SSN" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="alert-danger" asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber"></label>
        <input class="form-control" asp-for="PhoneNumber" />
        <span class="alert-danger" asp-validation-for="PhoneNumber"></span>
    </div>
    <div class="form-group">
        <label asp-for="CityId"></label>
        <input class="form-control" asp-for="CityId" />
        <span class="alert-danger" asp-validation-for="CityId"></span>
    </div>
    <button class="form-control btn btn-primary" type="submit"> Update Person </button>
</form>


    <div>
        <a asp-action="Index">Back person List</a>
    </div>


</div>

ASP.NET Core Empty Project/Views/PeopleDb/Index.cshtml
@model PeopleViewModelDb
@{
    ViewData["Title"] = "Index";
}


<div class="container">
    <h1>People</h1>

    @if (User.IsInRole("Admin"))
    {
        <p>Hello Admin! You can delete a person</p>

        <form asp-controller="PeopleDb" asp-action="DeletePerson" method="post" role="form">
            <br />
            <label for="ssn">Enter SSN:</label>
            <input type="text" name="ssn" />
            <input type="submit" class="btn btn-primary" name="btnFilter" value="delete" />
        </form>
    }

    <table class="table">
        <thead>
            <tr>
                <th>SSN</th>
                <th>Name</th>
                <th>PhoneNr</th>
                <th>City Id</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PeopleListView)
            {
                <tr>
                    <td>@item.SSN</td>
                    <td>@item.Name</td>
                    <td>@item.PhoneNr</td>
                    <td>@item.CityId</td>
                </tr>
            }
        </tbody>
    </table>

    <a class="btn btn-primary" asp-area="" asp-controller="PeopleDb" asp-action="CreatePerson">Create a Person</a>
    <a class="btn btn-primary" asp-area="" asp-controller="PeopleDb" asp-action="EditPerson">Edit a person</a>
</div>

ASP.NET Core Empty Project/Views/PeopleDb/Search.cshtml
@model PeopleViewModelDb
@{
    ViewData["Title"] = "Search";
}

<h2>Search</h2>

<table class="table">
    <thead>
        <tr>
            <th>SSN</th>
            <th>Name</th>
            <th>PhoneNr</th>
            <th>City Id</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.PeopleListView)
        {
            <tr>
                <td>@item.SSN</td>
                <td>@item.Name</td>
                <td>@item.PhoneNr</td>
                <td>@item.CityId</td>
            </tr>
        }
    </tbody>
</table>